---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: starboard
  name: starboard

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: starboard
  name: starboard
  namespace: starboard

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: starboard
  name: starboard-reconciler
  namespace: starboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: starboard-full-access
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:starboard:reconciler
  - kind: ServiceAccount
    name: starboard
    namespace: starboard
