---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.1.4
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: ingress-nginx
  values:
    controller:
      replicaCount: 3
      hostPort:
        enabled: true
      metrics:
        service:
          annotations:
            ingressClassName: nginx
      resources:
        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 9
