---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
