---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: cert-manager
  name: cert-manager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: cert-manager
  name: cert-manager
  namespace: cert-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: cert-manager
  name: cert-manager-reconciler
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:cert-manager:reconciler
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager

