---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard
  namespace: flux-system
spec:
  chart:
    spec:
      chart: starboard-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
      version: 0.6.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: starboard

