---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: example-app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/mkoellges/example-app
  ref:
    branch: main
