---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/mkoellges/weave-gitops.git
