---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: activem
  namespace: activemq-system
spec:
  chart:
    spec:
      chart: activemq
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: activemq
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: activemq-system

