---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: activemq-artemis
  namespace: activemq-system
spec:
  interval: 1m0s
  url: https://github.com/vromero/activemq-artemis-helm
