---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: activemq-artemis
  namespace: activemq-system
spec:
  interval: 1m0s
  url: https://vromero.github.io/activemq-artemis-helm/
