---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: app
  sourceRef:
    kind: GitRepository
    name: react-app
    namespace: flux-system
  path: "./deploy/manifests"
  prune: true
