---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: cert-manager
  targetNamespace: cert-manager
