---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  interval: 1m0s
  path: ./k8s/cluster-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-issuer
