---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: weave-gitops
  name: weave-gitops

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: weave-gitops
  name: weave-gitops
  namespace: weave-gitops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: weave-gitops
  name: weave-gitops-reconciler
  namespace: weave-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-gitops-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:weave-gitops:reconciler
- kind: ServiceAccount
  name: weave-gitops
  namespace: weave-gitops

