---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring

resources:
  - namespace.yaml
  - git-source.yaml
  - monitoring-kustomization.yaml
  - loki.yaml
  - grafana-dashboards.yaml
  - ingress.yaml
