---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-app-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlay/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app
  targetNamespace: example-app-dev
