---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: example-app-staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: staging
  url: https://github.com/mkoellges/example-app.git
