---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-app-staging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlay/staging
  prune: false
  sourceRef:
    kind: GitRepository
    name: example-app-staging
  targetNamespace: example-app-staging
