---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-exporter
  namespace: starboard
spec:
  chart:
    spec:
      chart: starboard-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: starboard
