---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: example-app-dev
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: dev
  url: https://github.com/mkoellges/example-app.git

