---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: monitoring
  name: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: monitoring
  name: monitoring
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: monitoring
  name: monitoring-reconciler
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:monitoring:reconciler
- kind: ServiceAccount
  name: monitoring
  namespace: monitoring

